name: Build mdBook Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          curl -L https://github.com/rust-lang/mdBook/releases/latest/download/mdbook-linux-amd64 -o mdbook
          chmod +x mdbook
          sudo mv mdbook /usr/local/bin/`

      - name: Make script executable
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh
